### ISSUE TITLE
IDEA 16 EAP: java.lang.NoSuchFieldError: EMPTY_FILE_SET

### ISSUE THREAD

**Issue by mfursov** [minman/wicketforge#169]
The plugin does not work with IDEA 16. The fix is very simple: create your own EMPTY_FILE_SET field instead of using openapi's one.

```
EMPTY_FILE_SET
java.lang.NoSuchFieldError: EMPTY_FILE_SET
	at wicketforge.search.AdditionalResourcePathsIndexProvider.getAdditionalRootsToIndex(AdditionalResourcePathsIndexProvider.java:55)
	at com.intellij.util.indexing.IndexableSetContributor.getRootsToIndex(IndexableSetContributor.java:45)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:2453)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFilesConcurrently(FileBasedIndexImpl.java:2409)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:75)
	at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:117)
	at com.intellij.openapi.project.DumbServiceImpl$11.run(DumbServiceImpl.java:488)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:479)
	at com.intellij.openapi.project.DumbServiceImpl.access$1600(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$10.run(DumbServiceImpl.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:374)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$2$1.run(PooledThreadExecutor.java:71)
```

**Comment by tgoetz** [comment]
A pull request would be great, if you already know how to fix this ... ;-)

**Comment by tgoetz** [comment]
Could you please release a new version? This bug seems to be fixed, it is currently still not possible to work with wicketforge in IntelliJ 16 EAP ...

**Comment by minman** [comment]
Ok, will release in a few days
